import Head from "next/head"
import NavBar from "../navbar"
import MastHead from "../header/"
import Footer from "../footer"
import myImageLoader from "../../loader"
export default function Layout({ children }) {
    return (
        <div className="flex flex-1 min-h-screen  flex-col items-center justify-center">
            <Head>
                <title>Create Next App</title>
                <meta name="CreLatorDesign" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <MastHead loader={myImageLoader} />
            <main className="flex w-full flex-1 flex-col items-center justify-center text-center">
                {children}
            </main>
            <Footer />
        </div>
    )
}
