import "../styles/globals.css"
import Head from "next/head"
import { Analytics } from "@vercel/analytics/react"

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Full Stack Developer</title>
                <meta
                    property="og:description"
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" name="title" content="Full Stack Developer" />
                <meta
                    property="og:image"
                    name="image"
                    content="https://firebasestorage.googleapis.com/v0/b/newlandingpage-918dc.appspot.com/o/images%2Favatar.svg?alt=media&token=8e5d9915-c16e-42ee-8506-365ed98ce3b7"
                />
                <meta name="author" content="Leonard Lator" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
            <Analytics />
        </>
    )
}

export default MyApp
