import "../styles/globals.css"
import Head from "next/head"
import { Analytics } from "@vercel/analytics/react"

function MyApp({ Component, pageProps }: { Component: any; pageProps: any }) {
    return (
        <>
            <Head>
                <title>Full Stack Developer</title>
                <meta
                    property="og:description"
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" name="title" content="Full Stack Developer" />
                <meta
                    name="image"
                    property="og:image"
                    content="https://www.leonardlator.dev/api/og"
                />
                <meta name="author" content="Leonard Lator" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
            <Analytics />
        </>
    )
}

export default MyApp
