import Head from "next/head"
import { useState, useEffect } from "react"
import NavBar from "../components/navbar"
import MastHead from "../components/header"
import Footer from "../components/footer"
import StackSection from "../components/stackSection"
import About from "../components/about"
import Portfolio from "../components/portfolio"
import Contact from "../components/contact"
// import clientPromise from "../lib/mongodb"
import myImageLoader from "../loader"
import useSWR from "swr"

const fetcher = (url) => fetch(url).then((res) => res.json())
export default function Home() {
    const [stackdata, setStackdata] = useState(null)
    const [isLoading, setIsLoading] = useState(true)

    const { data, error } = useSWR("/api/hello", fetcher)
    useEffect(() => {
        if (stackdata) setIsLoading(true)
        //     // fetch("/api/hello")
        //     //     .then((res) => res.json())
        //     //     .then((data) => {

        setStackdata(data)
        setIsLoading(false)
        //     // })
    }, [])

    if (error) return <div>Loading...</div>
    if (!data) return null

    return (
        <div className="flex flex-1 min-h-screen  flex-col items-center justify-center scroll-smooth">
            <Head>
                <title>Create Next App</title>
                <meta name="CreLatorDesign" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <MastHead loader={myImageLoader} />

            <main className="flex w-full flex-1 flex-col items-center justify-center text-center">
                <StackSection data={data} loader={myImageLoader} />
                <About />
                <Portfolio loader={myImageLoader} />
                <Contact />
            </main>

            <Footer />
        </div>
    )
}
